spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-request-size: 100MB
#      max-file-size: 10MB
  mail:
    # 发送邮件的服务器主机地址
    host: smtp.qq.com
    # 邮箱
    username: 412790423@qq.com
    # 这个密码是第三方服务的授权码，并不是QQ密码
    password: cllpsxgwfmqibjje
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        debug: true
